apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 662104234750.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 662104234750.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
